#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 12 20:09:05 2020
@author: armandbidault
"""
'''
#// ---------------- DEBUT EN TETE -------------------------------------//
// NOM : hauteur de l'eau en fonction de la marré                       //
// ALGO - REFERENCES :                                                  //
//                                                                      //
// AUTEURS : A.Bidault                                                  //
// VERSION :    1.0         P.SCHOTT              novembre 2020         // 
//                  Création en Scilab d'après le programme de mélanges //
// HISTORIQUE : Aucun                                                   //
//                                                                      //
// ENTREES :  hauteur dû a la marré et zero hydrographique.             //
//                                                                      //
// SORTIES : Hauteur de l'eau exacte                                    //
//                                                                      //
// MODIFIEES :                                                          //
//                                                                      //
// LOCALES :                                                            //
//                                                                      //
// FONCTIONS APPELEES :                                                 //
//                                                                      //
// ---------------- FIN EN TETE ----------------------------------------//
'''

print('\033[0m')
zero_hydrographique = float(input("veuillez rentrer le zéro hydrographique :"))
a = float(input("hauteur d'eau basse mer :"))   # on rentre les valeurs connues de la hauteur d'eau pour en déterminer leur interpolation 
b = float(input("hauteur d'eau h-5 :"))
c = float(input("hauteur d'eau h-4 :"))
d = float(input("hauteur d'eau h-3 :"))
e = float(input("hauteur d'eau h-2 :"))
f = float(input("hauteur d'eau h-1 :"))
g = float(input("hauteur d'eau pleine mer :"))
h = f
i = e
j = d
k = c
l = b
m = a
import matplotlib.pyplot as plt
from scipy import interpolate
import numpy as np
x = np.arange(0, 13)
y = np.array([a,b,c,d,e,f,g,h,i,j,k,l,m])
print(x)                                      # vérification de la taille des listes
print(y)
f = interpolate.interp1d(x, y, kind='cubic')  # cubic => interpolation par polynômes linéaire => fonction dérivable sur ]0;12[

xnew = np.arange(0, 12, 0.1)
ynew = f(xnew)   # utilisation de l'interpolation fonction returned by `interp1d`
plt.plot(x, y, 'o', xnew, ynew, '-')
plt.show()

V = float(input("quel temps exacte de la marée (en heure)voulez vous? "))  # on choisit ici la valeur a sortir de la fonction d'interpolation 
print("voici la hauteur d'eau dû a la marée actuelle", f(V))

H_f = zero_hydrographique + f(V)

print("*\n"*5)
print ('\033[47m' + '\033[31m' + "la hauteur d'eau sera de", H_f,"metres à", V,"heure de marée")
print('\033[0m')
print("*\n"*5)
